version: '3'
services:
  api:
    env_file:
      - "app/.env"
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #args:
      #  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      #  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      #  - AWS_DEFAULT_OUTPUT=${AWS_DEFAULT_OUTPUT}  
    image: poptape/authy/api:v0.3
    ports:
      - "1234:8001"
    restart: always
    volumes:
      - /var/log:/authy/log
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - net_poptape
  db:
    image: poptape/authy/db:v0.1
    restart: always
    env_file:
      - "app/.env"
#    environment:
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "1235:5432"
    volumes:
      - poptape_authdata:/var/lib/postgresql/data
    networks:
      - net_poptape
networks:
  net_poptape:
    external: true
volumes:
  poptape_authdata:
  
