version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/authy/api:v0.3
    ports:
      - "1234:8001"
    restart: always
    volumes:
      - /var/log:${LOGFILE}
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - net_poptape
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "1235:5432"
    volumes:
      - poptape_authdata:/var/lib/postgresql/data
    networks:
      - net_poptape
networks:
  net_poptape:
    external: true
volumes:
  poptape_authdata:
  
